# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Mjc0MTVkY2U0MzZmN2M3YmYzMzVmODdiMGRjMjAzYzI2M2VmMmQ3NzY2MzNjNWMzY2I4MTk0OWYyNjIwNjk0ZTA5Y2NlNTMyNWQxNWRhNGVjMTZmNmU3YjVmOGJkNDFlYjc5ZTg3NTY2NjE5YzQ0ODFiM2UzYTFiN2Q1MDg5ZWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
